### ISSUE TITLE
Admin Power Pack Not Loading for Admin User

### ISSUE THREAD

**Issue by sheyd** [looker-open-source/admin_power_pack#1]
When navigating to Admin Power Pack (fresh install after removing both original install and dummy connector), all admins get the following error page:

![Screen Shot 2022-06-24 at 12 08 01 PM](https://user-images.githubusercontent.com/4562565/175574570-ae4ecfb1-7fe4-4ea0-b51f-e21bc7debf7e.png)

Console errors don't show much, attaching log here.

[looker.com-1656086949878.log](https://github.com/looker-open-source/admin_power_pack/files/8977565/looker.com-1656086949878.log)

This has been an issue Looker versions `22.8` and `22.10`.

Things worked correctly with `22.6`.

**Comment by dongseok-kil** [comment]
same here

My console says
> looker_admin_power_pack.js:35 TypeError: Cannot read properties of undefined (reading 'includes')
    at looker_admin_power_pack.js:35:310337
    at Array.filter (<anonymous>)
    at looker_admin_power_pack.js:35:310316

how can I fix it?

**Comment by davidtamaki** [comment]
Apologies for the delay, this has been fixed in the latest release [v1.0.3](https://github.com/looker-open-source/admin_power_pack/releases/tag/v1.0.3)

If you've followed the marketplace install, you can reinstall APP (navigate to Marketplace => Manage, and remove and re-add the tool)

If you're using the `url` parameter to point to the [GitHub Pages hosted version](https://looker-open-source.github.io/admin_power_pack/dist/looker_admin_power_pack.js) of this extension then no action is required, this should now work as expected
